version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm test
          environment:
              JUNIT_REPORT_PATH: ./junit/
              JUNIT_REPORT_NAME: test-results.xml
      - store_test_results:
          path: ./junit