#!/bin/sh

export TEST_TYPE=
export SPEC_LIST="$1"
KARMA="./node_modules/karma/bin/karma"

if [ "$SPEC_LIST" = "view" ]; then
    TEST_TYPE="view"
    SPEC_LIST="$2"
fi

if ! [ "$SPEC_LIST" = "" ]; then
    SPEC_LIST="./test/$SPEC_LIST.spec.ts"
fi

$KARMA start --single-run
